spring:
  profiles:
    default: local
  datasource:
    url: ${DB_URL}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        ddl-auto: update
        show_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true

jwt:
  secret:
    key:
      ${JWT_KEY}

admin:
  token:
    ${ADMIN_TOKEN}

#profile:
#  image:
#    directory: "your/profile/image/directory"

logging:
  level:
    root: info
    com:
      example: debug
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql: trace


---

spring:
  config:
    activate:
      on-profile: test

  # DATABASE
  datasource:
    url: jdbc:mysql://localhost:3306/nullnull?serverTimezone=UTC&characterEncoding=UTF-8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 1026baby
  # JPA
  jpa:
    properties:
      hibernate:
        # INIT
        ddl-auto: create-drop
        # DEV
        # ddl-auto: update # Only 'create' when init
        show_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
# JWT

jwt:
  secret:
    key:
      1a1b9536d65432b16d4ded7f2814c8e5105ceae7ced4e173b086c564f2efa609d03c8ab84a78492f3175c0ce8ef792d6e55157f34777628f6f55163ef115bfe4

admin:
  token:
    11